version: '3.8'

services:
  postgres-db:
    image: postgres:15-alpine
    container_name: budget-postgres-container
    environment:
      POSTGRES_DB: budget_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  spring-app:
    build: .
    container_name: budget-spring-app-container
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/budget_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - postgres-db

volumes:
  postgres_data: